# RuboCop Configuration for Rails Architect

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

# Cop configurations
Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 100

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

